
// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// USER
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// BTJ_DRAWS
export const CREATE_BTJ_DRAWS_SUCCESS = "CREATE_BTJ_DRAWS_SUCCESS";
export const DELETE_BTJ_DRAWS_SUCCESS = "DELETE_BTJ_DRAWS_SUCCESS";
export const GET_BTJ_DRAWS_SUCCESS = "GET_BTJ_DRAWS_SUCCESS";
export const LIST_BTJ_DRAWS_SUCCESS = "LIST_BTJ_DRAWS_SUCCESS";
export const UPDATE_BTJ_DRAWS_SUCCESS = "UPDATE_BTJ_DRAWS_SUCCESS";

// BTJ_GAME_SETTINGS
export const CREATE_BTJ_GAME_SETTINGS_SUCCESS = "CREATE_BTJ_GAME_SETTINGS_SUCCESS";
export const DELETE_BTJ_GAME_SETTINGS_SUCCESS = "DELETE_BTJ_GAME_SETTINGS_SUCCESS";
export const GET_BTJ_GAME_SETTINGS_SUCCESS = "GET_BTJ_GAME_SETTINGS_SUCCESS";
export const LIST_BTJ_GAME_SETTINGS_SUCCESS = "LIST_BTJ_GAME_SETTINGS_SUCCESS";
export const UPDATE_BTJ_GAME_SETTINGS_SUCCESS = "UPDATE_BTJ_GAME_SETTINGS_SUCCESS";

// BTJ_MERCHANTS
export const CREATE_BTJ_MERCHANTS_SUCCESS = "CREATE_BTJ_MERCHANTS_SUCCESS";
export const DELETE_BTJ_MERCHANTS_SUCCESS = "DELETE_BTJ_MERCHANTS_SUCCESS";
export const GET_BTJ_MERCHANTS_SUCCESS = "GET_BTJ_MERCHANTS_SUCCESS";
export const LIST_BTJ_MERCHANTS_SUCCESS = "LIST_BTJ_MERCHANTS_SUCCESS";
export const UPDATE_BTJ_MERCHANTS_SUCCESS = "UPDATE_BTJ_MERCHANTS_SUCCESS";

// BTJ_TRANSACTIONS_ALL
export const CREATE_BTJ_TRANSACTIONS_ALL_SUCCESS = "CREATE_BTJ_TRANSACTIONS_ALL_SUCCESS";
export const DELETE_BTJ_TRANSACTIONS_ALL_SUCCESS = "DELETE_BTJ_TRANSACTIONS_ALL_SUCCESS";
export const GET_BTJ_TRANSACTIONS_ALL_SUCCESS = "GET_BTJ_TRANSACTIONS_ALL_SUCCESS";
export const LIST_BTJ_TRANSACTIONS_ALL_SUCCESS = "LIST_BTJ_TRANSACTIONS_ALL_SUCCESS";
export const UPDATE_BTJ_TRANSACTIONS_ALL_SUCCESS = "UPDATE_BTJ_TRANSACTIONS_ALL_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
